name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run Unit Tests
        run: |
          cd $HOME/project/TOMO-Financial-Buddy/backend
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest
          pytest

      - name: Run Deploy Script
        run: |
          cd $HOME/project/TOMO-Financial-Buddy
          bash deploy.sh
